name: 'Asana task updates'
description: 'Update asana tasks taken from comment or from inputs'
inputs:
  token:
    description: 'Personal token from Asana'
    required: true
  section:
    description: 'Section id in Asana project'
    required: true
  comment:
    description: 'Comment to find asana tasks'
    required: false
  project-id:
    description: 'Id of project in Asana'
    required: false
  task-id:
    description: 'Id of task in Asana'
    required: false
  updates:
    description: 'Tasks updates to run'
    required: false
    default: 'all'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - '-token'
    - ${{ inputs.token }}
    - '-section'
    - ${{ inputs.section }}
    - '-comment'
    - ${{ inputs.comment }}
    - '-project-id'
    - ${{ inputs.project-id }}
    - '-task-id'
    - ${{ inputs.task-id }}
    - '-updates'
    - ${{ inputs.updates }}